### ISSUE TITLE
Request for a next build please

### ISSUE THREAD

**Issue by Sam3740YT** [mmozeiko/build-mesa#3]
Hello, I have some problems compiling mesa with static libraries, at the moment I only use dynamic libraries, the problem is that some programs do not allow dynamic libraries.

I have used your builds and they work, but in some programs it creates graphical anomalies.

Do you think that for a future compilation you can add some commands that are the ones I use to solve these problems please?

meson setup build/ --prefix=/c/tmp/mesa --buildtype=release -Dgallium-drivers=swrast -Dshared-glapi=false -Dllvm=enabled -Dosmesa=true -Dglx=auto -Dgles-lib-suffix= true -Ddraw-use-llvm=true -Dshared-llvm=enabled

**Comment by mmozeiko** [comment]
I do not want to build static libraries. Because they will depend on compiler version/settings. I wanted this repo to provide me easy to get standalone dynamic libraries - with no dependency on compiler or other dll files. If you want static libs, just run the build locally.

Also I'm not sure what is the difference from meson command line you posted from what I have. Only difference seems to be for using shared libraries of llvm? That would be even more annoying to use, as that requires matching/compatible llvm version with what mesa code is built.
